# Uncomment the next line to define a global platform for your project
# platform :ios, '14.0'

target 'ML' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ML
  pod 'lottie-ios'
  pod 'Alamofire', '~> 5.5'


end
